"""
deck_data.py: the 53-slide DECK spec for build_pptx.py.

Each entry is a plain dict consumed by one archetype renderer. Content
mirrors the HTML reference deck (gen_50.py). All figures are illustrative
placeholders for the reference template.
"""

TAG_HI = "High"
TAG_MED = "Medium"
TAG_WATCH = "Watch"
TAG_LOW = "Low"

DECK = [
    # ===== FRONT MATTER (1-4) =====
    {"type": "cover_meeting", "sec": "front"},
    {"type": "agenda", "sec": "front", "kicker": "Agenda",
     "h": "Six sections, from **where the market is** to **what to do next**.",
     "desc": "This brief follows a single line: diagnose the gap, reframe the "
             "solution as a platform, then lay out the architecture, plan, and investment.",
     "sections": [
        ("01", "Context", "Slides 05\u201313", ["Market adoption signals", "Landscape of approaches", "Where teams sit today", "A client's starting point"]),
        ("02", "The problem", "Slides 14\u201322", ["Cost of delay", "Three root causes", "The broken path", "What compounds it"]),
        ("03", "The solution", "Slides 23\u201331", ["The reference stack", "Operating principles", "The governed path", "Objections answered"]),
        ("04", "Architecture", "Slides 32\u201339", ["Component diagram", "Runtime layer detail", "CI/CD with gates", "Build options"]),
        ("05", "The plan", "Slides 40\u201345", ["Modernization roadmap", "Assessment timeline", "The engagement team", "Ownership and risks"]),
        ("06", "Investment", "Slides 46\u201348", ["Engagement sizes", "The ask", "The recommendation"]),
     ],
     "src": "**Navigation \u00b7** Section dividers mark each transition. Read in order or sample by section."},
    {"type": "exec_summary", "sec": "front", "kicker": "Executive summary",
     "h": "Three things to take from this brief, **before the detail**.",
     "desc": "If the room reads only one slide, it is this one. Each column is a "
             "claim, the evidence behind it, and what it means for the decision ahead.",
     "cols": [
        ("1", "The blocker is the platform, not the model",
         "Pilots reach a working demo and stall. The recurring cause is the absence of a shared foundation: environments, data access, and a route to production.",
         "**So what \u00b7** Solve it once at the platform layer, not repeatedly per project."),
        ("2", "An opinionated stack closes the gap",
         "Four layers, each owned once, remove the friction line-items teams hit today. Teams consume the platform; they do not re-derive it.",
         "**So what \u00b7** The reference architecture is the deliverable, not a slideware idea."),
        ("3", "Start small, decide on evidence",
         "A three-week assessment produces the client's own baseline. Every commitment after that is a decision made with real numbers.",
         "**So what \u00b7** Low-commitment first step. The roadmap earns the next phase."),
     ],
     "src": "**Read order \u00b7** This slide stands alone. The six sections expand each column."},
    {"type": "quote", "sec": "front",
     "quote": "The hard part of enterprise AI was never the model. It is the "
              "distance between a notebook and a service the business can "
              "actually depend on.",
     "cite": "Framing position \u00b7 **reference template**, illustrative attribution"},

    # ===== SECTION 1 · CONTEXT (5-13) =====
    {"type": "divider", "sec": "ctx", "act_no": "I", "kicker": "Section 1 \u00b7 Context",
     "title": "Where the market is on production AI",
     "desc": "Adoption is wide and shallow. Pilots are everywhere; production "
             "is rare. This section sizes that gap before naming its causes.",
     "questions": ["How wide is AI adoption, really?", "How narrow is production?",
                   "Where does the typical team sit?"], "q_start": 1},
    {"type": "section_intro", "sec": "ctx", "kicker": "Section intro",
     "h": "Where the market is, in **one honest read**.",
     "desc": "A section intro is lighter than a divider; it sets up the sub-topic.",
     "eyebrow": "What this section covers",
     "statement": "Adoption is wide. **Production is narrow.**",
     "lead": "Most enterprises now run AI pilots. Far fewer run AI in production. "
             "This section sizes that gap with the client's peers as the "
             "reference point, so the problem is concrete before we name its causes.",
     "aside": [("In this section", "4 slides, ending on a client snapshot"),
               ("Key question", "How big is the pilot-to-production gap?"),
               ("Leaves you with", "A measured starting point, not an opinion")],
     "src": "**Pattern note \u00b7** Use a section intro after a divider when the section is long."},
    {"type": "big_number", "sec": "ctx", "kicker": "Adoption signal",
     "h": "Almost everyone is **piloting**. Almost no one is shipping.",
     "desc": "The headline gap is not interest in AI. It is the distance between "
             "a team that runs experiments and a team that runs services.",
     "metric_label": "The core metric", "metric_n": "9", "metric_unit": "/10",
     "metric_desc": "enterprises in this scenario run at least one AI pilot. Illustrative figure.",
     "cards": [("Reach a demo", "~80%", "of pilots produce a working demonstration of value.", ""),
               ("Reach production", "~12%", "of those demos become a governed, monitored service.", ""),
               ("The drop", "1", "platform layer separates the two numbers above.", "accent")],
     "src": "**Note \u00b7** All figures are placeholders. Real client decks must cite named, dated sources."},
    {"type": "metrics_dashboard", "sec": "ctx", "kicker": "Context metrics",
     "h": "Four signals that **size the gap** before we explain it.",
     "desc": "A dashboard mixes one headline metric with supporting context.",
     "featured": ("Headline signal", "12", "%", "of AI pilots in this scenario reach a governed production deployment."),
     "tiles": [("Pilots running", "~9", "/10", "enterprises run at least one AI pilot"),
               ("Demo success", "~80", "%", "of pilots reach a working demo"),
               ("Time to prod", "9", "wks", "median, on ad hoc infrastructure"),
               ("Teams diverging", "6+", "", "distinct setups across one org")],
     "src": "**Dashboard note \u00b7** All figures are placeholders for the reference template."},
    {"type": "data_table", "sec": "ctx", "kicker": "The landscape",
     "h": "Four ways teams approach AI infrastructure today, and **what each costs**.",
     "desc": "A side-by-side of the common patterns. Most teams are somewhere in "
             "the first two rows, and that is the problem.",
     "headers": [("Approach", "l", 0.24), ("Who does it", "l", 0.16),
                 ("What it optimizes for", "l", 0.30), ("Recurs", "num", 0.13),
                 ("Maturity", "l", 0.17)],
     "rows": [
        [("Per-project setup", "bold"), ("Each app team", None),
         ("Speed of the first demo", None), ("Per project", "num"), ("Low", "tag")],
        [("Shared scripts", "bold"), ("A platform champion", None),
         ("Reuse, informally", None), ("Per team", "num"), ("Medium", "tag")],
        [("Cloud-managed PaaS", "bold"), ("Vendor", None),
         ("Time to first deploy", None), ("Per workload", "num"), ("Medium", "tag")],
        [("Reference platform", "bold"), ("Owned once, consumed by all", None),
         ("Repeatable path to production", None), ("Once", "num"), ("High", "tag")],
     ],
     "pull": ("Read this as", "Maturity rises only when the platform is **owned "
              "once** instead of rebuilt per project. That is the move this brief argues for.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Maturity banding** is qualitative. Replace with the client's own assessment."},
    {"type": "quadrant", "sec": "ctx", "kicker": "Where teams sit today",
     "h": "Most AI work clusters in the **wrong quadrant**: high ambition, low readiness.",
     "desc": "A simple read of the field. Vertical axis is platform maturity; "
             "horizontal is AI ambition. The gap is the distance teams must close.",
     "yaxis": "Platform maturity \u2192", "xaxis": "AI ambition \u2192",
     "cells": [("Top left", "Over-built", "Strong platform, little AI demand on it yet.", False),
               ("Top right \u00b7 target", "Production-ready", "Platform maturity matches AI ambition.", True),
               ("Bottom left", "Early days", "Low on both axes. Honest starting point.", False),
               ("Bottom right \u00b7 where most sit", "Ambition outruns foundation", "High AI ambition, thin platform.", False)],
     "dots": [("them", "31%", "34%"), ("us", "74%", "71%")],
     "legend": [("red", "Typical client today"), ("silver", "Peer benchmark")],
     "src": "**Axis note \u00b7** Replace dot positions with the client's own self-assessment scores."},
    {"type": "before_after", "sec": "ctx", "kicker": "Expectation vs reality",
     "h": "What teams **expect** from an AI pilot, and what they **get**.",
     "desc": "The gap between the two columns is not failure. It is the "
             "predictable result of building without a platform.",
     "before_label": "Expectation \u00b7 going in",
     "before_items": ["A pilot proves value in weeks.",
                      "A successful demo ships to production.",
                      "The next pilot reuses the first one's work.",
                      "Governance is a final checkbox.",
                      "Cost and behavior are visible by default."],
     "after_label": "Reality \u00b7 without a platform",
     "after_items": ["The demo works; the path to production does not.",
                     "The demo stalls waiting for infrastructure.",
                     "The next pilot starts from zero again.",
                     "Governance is a late, expensive surprise.",
                     "Cost and behavior live in scattered places."],
     "stats": [("Demos that ship", "~12%", "reach production"),
               ("Setup, repeated", "Per pilot", "not once"),
               ("Gap", "Predictable", "and fixable", True)],
     "src": "**Outcome figures** are directional placeholders. Validate against a client baseline."},
    {"type": "case_study", "sec": "ctx", "kicker": "Case study",
     "h": "One client, **same shape of problem**, measured before and after.",
     "desc": "A case study makes the abstract concrete. Problem, approach, "
             "result, with the headline outcome in the hero panel.",
     "hero_tag": "Reference client", "hero_name": "Mid-size financial services firm",
     "hero_meta": "~600 engineers \u00b7 existing Azure footprint \u00b7 12 AI pilots, 1 in production",
     "hero_stat_n": "9 \u2192 2", "hero_stat_l": "weeks to provision a new AI workload, after the platform",
     "steps": [("Problem", "Every pilot rebuilt its own environment and data access. **Eleven of twelve** never got a production target."),
               ("Approach", "A six-week foundation phase: AKS landing zone, standard pipeline, and one pilot migrated onto golden paths."),
               ("Result", "Provisioning dropped from **nine weeks to two**. Three further workloads reached production within the next quarter.")],
     "src": "**Anonymization note \u00b7** Figures and client descriptor are illustrative."},
    {"type": "stakeholder_map", "sec": "ctx", "kicker": "Stakeholder map",
     "h": "Who to **engage closely**, and who to keep informed.",
     "desc": "A stakeholder map plots influence against interest. The top-right "
             "quadrant is where the engagement spends its attention.",
     "yaxis": "Influence \u2192", "xaxis": "Interest \u2192",
     "cells": [("High influence \u00b7 low interest", ["CFO", "Procurement"], False),
               ("High influence \u00b7 high interest \u00b7 engage closely", ["CTO", "Head of platform", "Security lead"], True),
               ("Low influence \u00b7 low interest \u00b7 monitor", ["Adjacent BUs"], False),
               ("Low influence \u00b7 high interest \u00b7 keep informed", ["App teams", "SRE", "Data engineering"], False)],
     "src": "**Map note \u00b7** Placement is illustrative. Build the real map with the client sponsor."},

    # ===== SECTION 2 · THE PROBLEM (14-22) =====
    {"type": "divider", "sec": "prob", "act_no": "II", "kicker": "Section 2 \u00b7 The problem",
     "title": "Why pilots stall before production",
     "desc": "The blocker is rarely the model. It is everything underneath: "
             "environments, data access, governance, and the route to a service.",
     "questions": ["Where exactly do pilots break down?", "What does the delay cost?",
                   "Is this a tooling problem or a platform problem?"], "q_start": 4},
    {"type": "big_number", "sec": "prob", "kicker": "The gap",
     "h": "Most teams reach a **working demo**. Far fewer reach a governed service.",
     "desc": "The distance between those two states is the platform gap. It "
             "shows up as repeated setup, inconsistent data access, and no standard route.",
     "metric_label": "The core metric", "metric_n": "68", "metric_unit": "%",
     "metric_desc": "of AI pilots in this scenario never get a production deployment target assigned.",
     "cards": [("Symptom 1 \u00b7 Environments", "~40h", "spent per team, per quarter, re-creating environments by hand.", ""),
               ("Symptom 2 \u00b7 Governance", "0", "consistent policy gates between an experiment and an endpoint.", ""),
               ("Root cause", "1", "missing platform layer. Every symptom traces back to it.", "accent")],
     "src": "**Note \u00b7** All figures are placeholders for the reference template."},
    {"type": "data_table", "sec": "prob", "kicker": "Cost of delay",
     "h": "The platform gap has a **line-item cost**. Here is where it accrues.",
     "desc": "Five recurring friction points, the team they tax, and the effect on delivery.",
     "headers": [("Friction point", "l", 0.24), ("Owner", "l", 0.16),
                 ("Effect on delivery", "l", 0.30), ("Recurs", "num", 0.13),
                 ("Severity", "l", 0.17)],
     "rows": [
        [("Manual environment setup", "bold"), ("Platform team", None),
         ("Each new workload restarts from zero infrastructure.", None),
         ("Per project", "num"), ("High", "tag")],
        [("Inconsistent data access", "bold"), ("Data engineering", None),
         ("Credentials and patterns differ across every team.", None),
         ("Per team", "num"), ("High", "tag")],
        [("No standard CI path", "bold"), ("App teams", None),
         ("Each repo invents its own build and release flow.", None),
         ("Per repo", "num"), ("Medium", "tag")],
        [("Governance applied late", "bold"), ("Security", None),
         ("Policy checks happen after build, forcing rework.", None),
         ("Per release", "num"), ("Medium", "tag")],
        [("Fragmented observability", "bold"), ("SRE", None),
         ("No shared view of cost, latency, or model behavior.", None),
         ("Continuous", "num"), ("Watch", "tag")],
     ],
     "pull": ("Read this as", "Every row is **solvable once** at the platform "
              "layer instead of **repeatedly** at the project layer.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Severity banding** is illustrative. Replace with the client's own incident data."},
    {"type": "pillar_grid", "sec": "prob", "kicker": "Root causes",
     "h": "Five symptoms, **three root causes**.",
     "desc": "The cost-of-delay table lists what teams feel. These are the three "
             "underlying causes that produce all of it.",
     "pillars": [
        ("01", "No shared foundation", "Every workload re-derives networking, identity, and a release path because nothing provides them by default."),
        ("02", "Governance bolted on", "Policy lives outside the delivery path, so it is discovered late and applied as rework rather than as a property of shipping."),
        ("03", "No common signal", "Cost, latency, and model behavior live in team-local dashboards, so problems surface in weeks instead of hours."),
     ],
     "src": "**Cause note \u00b7** Three is deliberate. A long list of causes is a list nobody acts on."},
    {"type": "flow", "sec": "prob", "kicker": "The broken path",
     "h": "Without a platform, the path to production **breaks at every hand-off**.",
     "desc": "Four stages, four points of friction. Each arrow is where a workload waits or stalls.",
     "nodes": [("1", "Scaffold", "Starts from an empty repo. Infrastructure negotiated by hand."),
               ("2", "Build", "Each team invents its own CI. No shared evaluation or policy."),
               ("3", "Deploy", "No standard runtime target. Networking and scaling re-decided."),
               ("4", "Operate", "Observability is team-local. Problems surface late.")],
     "src": "**Flow note \u00b7** Compare this to the governed path in the next section, stage for stage."},
    {"type": "risks_table", "sec": "prob", "kicker": "What compounds it",
     "h": "The problem does not sit still. **Four things make it worse** over time.",
     "desc": "Left alone, the platform gap compounds. Each row is a force that widens it.",
     "rows": [
        ("Each new pilot adds debt", TAG_HI, TAG_HI,
         "Every project built the old way is one more thing to migrate later."),
        ("Teams diverge further", TAG_HI, TAG_MED,
         "Without a shared path, each team's setup drifts further from every other."),
        ("Governance debt accrues", TAG_MED, TAG_HI,
         "Late policy means rework piles up release after release."),
        ("Knowledge stays siloed", TAG_MED, TAG_MED,
         "What one team learns the hard way, the next team learns again."),
     ],
     "pull": ("Why this matters now", "The gap is cheapest to close **today**. "
              "Every quarter of delay adds workloads to migrate and divergence to undo.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Banding note \u00b7** Likelihood and impact are qualitative. Calibrate with the client."},
    {"type": "quote", "sec": "prob",
     "quote": "We did not have an AI problem. We had twelve different "
              "definitions of what it meant to put a model in production.",
     "cite": "Practitioner voice \u00b7 **reference template**, illustrative attribution"},
    {"type": "exec_summary", "sec": "prob", "kicker": "Problem recap",
     "h": "The problem in **three lines**, before we turn to the solution.",
     "desc": "A mid-deck recap. If the room lost the thread, this is where it picks back up.",
     "cols": [
        ("1", "It is a platform problem", "Not a model problem, not a talent problem. The blocker is the absence of a shared foundation.",
         "**So what \u00b7** The fix is structural, not another pilot."),
        ("2", "It has a real cost", "Repeated setup, late governance, fragmented signal. Measurable, and paid every quarter.",
         "**So what \u00b7** Inaction is not free; it compounds."),
        ("3", "It compounds", "Every quarter of delay adds workloads to migrate and divergence to undo.",
         "**So what \u00b7** The cheapest time to act is now."),
     ],
     "src": "**Recap note \u00b7** This mirrors the front-matter exec summary, refocused on the problem."},
    {"type": "section_intro", "sec": "prob", "kicker": "Section intro",
     "h": "From symptoms to **a single cause**.",
     "desc": "A bridge slide: the problem is named, the solution comes next.",
     "eyebrow": "Where this section lands",
     "statement": "Every friction point traces to **one missing layer.**",
     "lead": "The cost-of-delay table and the root-cause analysis converge on the "
             "same conclusion. The next section names the layer that is missing "
             "and shows what it looks like when it exists.",
     "aside": [("Just covered", "Cost of delay, root causes, what compounds it"),
               ("Coming next", "The reference platform, layer by layer"),
               ("The hinge", "Platform as the unit of delivery")],
     "src": "**Pattern note \u00b7** A section intro can also close a section by pointing forward."},
]

# ===== SECTION 3 · THE SOLUTION (23-31) =====
DECK += [
    {"type": "divider", "sec": "sol", "act_no": "III", "kicker": "Section 3 \u00b7 The solution",
     "title": "Platform as the unit of delivery",
     "desc": "Stop shipping AI projects. Start shipping a platform that makes "
             "the next AI project boring, fast, and governed by default.",
     "questions": ["What does the reference stack look like?",
                   "What changes for the teams using it?",
                   "What about the obvious objections?"], "q_start": 8},
    {"type": "section_intro", "sec": "sol", "kicker": "Section intro",
     "h": "The fix is **a layer, not a project**.",
     "desc": "This section names the missing layer and shows it working.",
     "eyebrow": "What this section covers",
     "statement": "One platform, **owned once, consumed by all.**",
     "lead": "The reference stack is four layers. Each removes a row from the "
             "cost-of-delay table. The rest of this section walks the stack, "
             "the principles that hold it together, and the objections it raises.",
     "aside": [("In this section", "The stack, principles, the governed path, FAQ"),
               ("Key shift", "From per-project setup to a shared platform"),
               ("Leaves you with", "A concrete architecture, not a concept")],
     "src": "**Pattern note \u00b7** Section intros keep a long section navigable."},
    {"type": "layer_stack", "sec": "sol", "kicker": "Reference stack",
     "h": "Four layers, **each owned once**, each removing a row from the cost-of-delay table.",
     "desc": "The stack is opinionated on purpose. Teams consume it; they do not "
             "re-derive it. Layer colors map to the Microsoft palette.",
     "layers": [
        ("Experience", "Developer portal & golden paths",
         "Self-service templates so a new AI workload starts from a governed baseline, not a blank repo."),
        ("Delivery", "Standard CI/CD with policy gates",
         "One build-and-release path. Governance runs inside the pipeline, not after it."),
        ("Runtime", "Azure Kubernetes Service landing zone",
         "A consistent place to run workloads, with networking, identity, and scaling decided once."),
        ("Intelligence", "Azure AI Foundry & model governance",
         "Shared model catalog, evaluation, and observability so every team sees cost and behavior the same way."),
     ],
     "src": "**Architecture note \u00b7** Layer names are generic. Real decks name the client's services."},
    {"type": "pillar_grid", "sec": "sol", "kicker": "Operating principles",
     "h": "The stack works because **three principles** hold it together.",
     "desc": "Architecture describes the what. These principles describe the how, "
             "and they keep the platform from drifting back into per-project chaos.",
     "pillars": [
        ("01", "Opinionated by default", "The platform makes the common choices so teams do not. A new workload inherits networking, identity, and a release path."),
        ("02", "Governed in the path", "Policy runs inside the pipeline, not as a gate discovered late. Compliance becomes a property of shipping."),
        ("03", "Observable end to end", "One shared view of cost, latency, and model behavior. Every team reads the same dashboard."),
     ],
     "src": "**Principle note \u00b7** These are deliberately few. A long list is a list nobody follows."},
    {"type": "before_after", "sec": "sol", "kicker": "Before / after",
     "h": "What changes for the teams **consuming the platform**.",
     "desc": "The platform layer is invisible when it works. The visible result "
             "is a different day-to-day for app teams, security, and SRE.",
     "before_label": "Before \u00b7 project-by-project",
     "before_items": ["New workload starts from an empty repository and a wiki page.",
                      "Each team negotiates its own data access and secrets.",
                      "Security review is a gate discovered late, near release.",
                      "Cost and latency live in scattered, team-local dashboards.",
                      "Production readiness is argued case by case."],
     "after_label": "After \u00b7 platform-as-default",
     "after_items": ["New workload starts from a golden-path template.",
                     "Data access patterns are inherited, not re-negotiated.",
                     "Policy gates run inside the standard pipeline.",
                     "One shared view of cost, latency, and model behavior.",
                     "Production readiness is a checklist the platform enforces."],
     "stats": [("Setup time", "\u221270%", "environment provisioning"),
               ("Policy rework", "\u22121 stage", "governance shifts left"),
               ("Time to prod", "Weeks \u2192 days", "directional outcome", True)],
     "src": "**Outcome figures** are directional placeholders. Validate against a client baseline."},
    {"type": "flow", "sec": "sol", "kicker": "The governed path",
     "h": "With the platform in place, a workload moves through **four governed stages**.",
     "desc": "Each stage has a clear owner and a clear hand-off. Nothing is "
             "improvised, and nothing waits on a meeting.",
     "nodes": [("1", "Scaffold", "Start from a golden-path template with identity and networking pre-wired."),
               ("2", "Build", "Standard CI runs tests, evaluations, and policy checks in one pass."),
               ("3", "Deploy", "Release to the AKS landing zone with scaling and rollback already defined."),
               ("4", "Operate", "Shared observability tracks cost, latency, and model behavior from day one.")],
     "src": "**Flow note \u00b7** This is the broken-path slide from Section 2, fixed stage for stage."},
    {"type": "metrics_dashboard", "sec": "sol", "kicker": "Target-state metrics",
     "h": "Six signals that tell you the platform is **actually working**.",
     "desc": "A dashboard mixes one headline metric with supporting context.",
     "featured": ("Headline signal", "2", "wks", "median time to provision a new AI workload, down from nine."),
     "tiles": [("Time to production", "\u221270", "%", "pilot to live service"),
               ("Policy rework", "\u22121", "stage", "governance shifted left"),
               ("Workloads on platform", "14", "", "across six teams"),
               ("Shared observability", "100", "%", "one pane, all teams")],
     "src": "**Dashboard note \u00b7** All figures are placeholders. Read against the Phase 1 baseline."},
    {"type": "case_study", "sec": "sol", "kicker": "Case study",
     "h": "The **same client**, after the platform was in place.",
     "desc": "The Context-section case study, revisited. Same firm, same metrics, "
             "measured after the foundation phase.",
     "hero_tag": "Reference client \u00b7 after", "hero_name": "Mid-size financial services firm",
     "hero_meta": "Same ~600 engineers \u00b7 platform live \u00b7 4 workloads in production",
     "hero_stat_n": "4 \u00d7", "hero_stat_l": "more workloads in production within one quarter of the platform going live",
     "steps": [("Before", "Twelve pilots, one in production. Every workload rebuilt its own environment."),
               ("Change", "A six-week foundation phase stood up the landing zone, the standard pipeline, and golden paths."),
               ("After", "Provisioning at **two weeks**, four workloads live, and the platform owned by the client team.")],
     "src": "**Anonymization note \u00b7** Figures and client descriptor are illustrative."},
    {"type": "faq", "sec": "sol", "kicker": "Common objections",
     "h": "The questions a careful buyer asks, **answered directly**.",
     "desc": "A FAQ slide pre-empts the room's real concerns. Six pairs, no evasion.",
     "items": [
        ("Does this replace our existing Azure setup?", "No. The assessment maps the current estate first, and the landing zone is designed **around what exists**, not on top of a teardown."),
        ("What if our teams resist a shared platform?", "Two pilot teams co-design the golden paths. The platform reflects **real workflows** because real teams shaped it."),
        ("How long until we see value?", "The Phase 1 assessment delivers a baseline in **three weeks**. The first workload runs end to end by week nine."),
        ("Who owns the platform afterwards?", "The client does. Client engineers work inside Phases 2 and 3, so ownership **transfers gradually**."),
        ("Is this locked to Microsoft tooling?", "The reference stack uses Azure services, but the patterns are portable. There is **no proprietary lock-in** layer."),
        ("What does it cost to run, ongoing?", "Runtime cost is the AKS and Foundry footprint. The platform itself adds **process, not licensing**."),
     ],
     "src": "**FAQ note \u00b7** Tailor the list to each client's known concerns."},

    # ===== SECTION 4 · ARCHITECTURE (32-39) =====
    {"type": "divider", "sec": "arch", "act_no": "IV", "kicker": "Section 4 \u00b7 Architecture",
     "title": "How it fits together",
     "desc": "The diagnosis and the reframe are settled. This section is the "
             "annotated architecture: real components, real decisions, in the open.",
     "questions": ["What are the components, concretely?",
                   "How does the pipeline enforce governance?",
                   "Build, buy, or reference platform?"], "q_start": 11},
    {"type": "section_intro", "sec": "arch", "kicker": "Section intro",
     "h": "From principles to **components**.",
     "desc": "This section gets concrete: named services, real wiring.",
     "eyebrow": "What this section covers",
     "statement": "The stack, **drawn out and annotated.**",
     "lead": "The solution section made the case. This section shows the wiring: "
             "the component diagram, the runtime layer in detail, the pipeline "
             "with its gates, and an honest build-versus-buy comparison.",
     "aside": [("In this section", "Component diagram, runtime detail, CI/CD, build options"),
               ("Audience", "The technical reviewers in the room"),
               ("Leaves you with", "Enough detail to challenge the design")],
     "src": "**Pattern note \u00b7** Section intros orient a technical audience before the detail."},
    {"type": "architecture_detail", "sec": "arch", "kicker": "Architecture detail",
     "h": "The reference stack, **component by component**, with the decisions called out.",
     "desc": "Where the layer-stack slide is the overview, this is the annotated "
             "version: real components in tiers, with design decisions as notes.",
     "tiers": [
        ("Experience", [("Developer portal", "Golden-path templates", "blue"),
                        ("Service catalog", "Self-service provisioning", "blue")]),
        ("Delivery", [("Standard CI", "Build, test, evaluate", "green"),
                      ("Policy gates", "In-pipeline governance", "green"),
                      ("Release", "Promotion with rollback", "green")]),
        ("Runtime & Intelligence", [("AKS landing zone", "Networking, identity, scale", "yellow"),
                                     ("Azure AI Foundry", "Model catalog, evaluation", "red"),
                                     ("Observability", "Cost, latency, behavior", "red")]),
     ],
     "notes": [("Decided once", "Networking and identity live in the landing zone, not per workload."),
               ("Shift-left by design", "Policy gates run inside CI, so governance is a property of shipping."),
               ("One pane", "Observability is shared, so every team reads the same signal.")],
     "src": "**Diagram note \u00b7** Component names are generic. Real decks name the client's services."},
    {"type": "layer_stack", "sec": "arch", "kicker": "Runtime layer, expanded",
     "h": "The runtime layer is where **most decisions get made once**.",
     "desc": "Zooming into the AKS landing zone: four concerns that every "
             "workload would otherwise re-decide, settled at the platform level.",
     "layers": [
        ("Networking", "Virtual network & ingress",
         "One network topology, one ingress pattern. Workloads attach; they do not design."),
        ("Identity", "Workload identity & secrets",
         "Managed identity and a single secrets pattern. No per-team credential negotiation."),
        ("Scaling", "Autoscaling & resource policy",
         "Scaling rules and resource quotas defined once, inherited by every namespace."),
        ("Isolation", "Namespace & policy boundaries",
         "Each team gets a bounded space with guardrails, not a blank cluster."),
     ],
     "src": "**Architecture note \u00b7** Component names are generic. Real decks name the client's services."},
    {"type": "flow", "sec": "arch", "kicker": "CI/CD with policy gates",
     "h": "The pipeline is where **governance becomes automatic**.",
     "desc": "Four stages, with policy embedded in stages two and three. Nothing "
             "reaches production without passing through them.",
     "nodes": [("1", "Commit", "Code and config land in a standard repo structure."),
               ("2", "Build & check", "Tests, model evaluation, and policy gates run in one pass."),
               ("3", "Promote", "Signed artifacts move through environments with rollback defined."),
               ("4", "Observe", "Cost, latency, and behavior stream to the shared dashboard.")],
     "src": "**Flow note \u00b7** Policy lives in stage 2. That placement is what shifts governance left."},
    {"type": "data_table", "sec": "arch", "kicker": "Service inventory",
     "h": "Every component, **by layer**, with its role and owner.",
     "desc": "The architecture diagram, written out as a table. The reference "
             "list a platform team works from.",
     "headers": [("Service", "l", 0.24), ("Layer", "l", 0.16),
                 ("Role", "l", 0.38), ("Owner", "l", 0.22)],
     "rows": [
        [("Developer portal", "bold"), ("Experience", None),
         ("Golden-path templates and self-service provisioning.", None), ("Platform team", None)],
        [("Standard CI/CD", "bold"), ("Delivery", None),
         ("Build, evaluate, gate, and promote in one path.", None), ("Platform team", None)],
        [("Policy engine", "bold"), ("Delivery", None),
         ("In-pipeline governance rules and enforcement.", None), ("Security", None)],
        [("AKS landing zone", "bold"), ("Runtime", None),
         ("Networking, identity, scaling, isolation.", None), ("Platform team", None)],
        [("Azure AI Foundry", "bold"), ("Intelligence", None),
         ("Model catalog, evaluation, and versioning.", None), ("Platform team", None)],
        [("Observability stack", "bold"), ("Intelligence", None),
         ("Shared cost, latency, and model-behavior signal.", None), ("SRE", None)],
     ],
     "pull": ("How to use this", "This table is the **build checklist**. Phase 2 "
              "stands up rows one to four; rows five and six follow in Phase 3.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Inventory note \u00b7** Services are generic. Real decks name specific SKUs and versions."},
    {"type": "vendor_compare", "sec": "arch", "kicker": "Build options",
     "h": "Three ways to get a platform. **One fits this client**.",
     "desc": "A vendor-compare slide is an honest feature matrix. The recommended "
             "column is highlighted, but every row is filled for all three.",
     "cap_label": "Capability",
     "options": [("Build in-house", False), ("Reference platform", True), ("Off-the-shelf PaaS", False)],
     "rows": [
        ("Time to first workload", ["no", "yes", "partial"]),
        ("Fits existing Azure estate", ["yes", "yes", "no"]),
        ("Governance in the pipeline", ["partial", "yes", "no"]),
        ("Client owns it at the end", ["yes", "yes", "no"]),
        ("Ongoing vendor lock-in", ["yes", "yes", "no"]),
        ("Internal effort to maintain", ["no", "partial", "yes"]),
     ],
     "pull": ("How to read this", "In-house gives control at a high cost. "
              "Off-the-shelf is fast but rents you the platform. The reference "
              "platform is the middle path: built with you, owned by you.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Matrix note \u00b7** Ratings are qualitative for the template. Real comparisons cite specifics."},
    {"type": "decision_matrix", "sec": "arch", "kicker": "Weighted decision",
     "h": "The build-versus-platform call, **scored on the criteria that matter**.",
     "desc": "A decision matrix shows the reasoning, not just the conclusion. "
             "Each option is scored against weighted criteria, computed in the open.",
     "headers": [("Criterion", False), ("Weight", True), ("Build in-house", True),
                 ("Reference platform", True), ("Off-the-shelf PaaS", True)],
     "rows": [
        ("Speed to production", ["30%", "1.2", "2.7", "2.4"]),
        ("Fit with current estate", ["25%", "2.3", "2.5", "1.0"]),
        ("Long-term ownership", ["25%", "2.5", "2.5", "0.8"]),
        ("Internal effort to sustain", ["20%", "0.8", "1.8", "2.4"]),
     ],
     "total": ("Weighted total", ["100%", "1.67", "2.41", "1.62"]),
     "pull": ("What the score says", "The reference platform wins not on any "
              "single row, but on **balance**: it is the only option that scores "
              "well on speed, fit, and ownership at once.",
              "Scoring is illustrative \u00b7 reference template"),
     "src": "**Scoring note \u00b7** Weights and scores are placeholders. Set them with the client."},

    # ===== SECTION 5 · THE PLAN (40-45) =====
    {"type": "divider", "sec": "plan", "act_no": "V", "kicker": "Section 5 \u00b7 The plan",
     "title": "From decision to a platform teams build on",
     "desc": "The architecture is settled. What remains is a staged path, a "
             "clear team, and an honest view of who owns what.",
     "questions": ["What is the staged path and timeline?",
                   "Who runs the engagement?",
                   "Who owns the platform afterward?"], "q_start": 14},
    {"type": "roadmap", "sec": "plan", "kicker": "Modernization roadmap",
     "h": "A **staged path** from assessment to a platform other teams build on.",
     "desc": "Each phase ends with something usable. No phase depends on the "
             "next one being perfect. Timeframes are indicative.",
     "phases": [
        ("Phase 1", "Assess", "Weeks 1-3",
         ["Map current AI workloads and blockers", "Baseline delivery and cost metrics", "Agree target platform scope"],
         "Exit criteria", "Signed-off **scope document** and a measured delivery baseline."),
        ("Phase 2", "Foundation", "Weeks 4-9",
         ["Stand up the AKS landing zone", "Establish identity and networking", "Wire the standard CI/CD path"],
         "Exit criteria", "One workload running through the **standard pipeline** end to end."),
        ("Phase 3", "Golden paths", "Weeks 10-16",
         ["Publish self-service templates", "Onboard two pilot teams", "Embed policy gates and observability"],
         "Exit criteria", "Two pilot teams shipping from **golden-path templates**."),
        ("Phase 4", "Scale", "Weeks 17+",
         ["Roll out to remaining teams", "Hand platform ownership to client", "Establish continuous improvement loop"],
         "Exit criteria", "Platform **owned by the client**, with an active improvement loop."),
     ],
     "src": "**Timeframes** assume a mid-size org with an existing Azure footprint. Re-scope per engagement."},
    {"type": "gantt", "sec": "plan", "kicker": "Detailed timeline",
     "h": "Twelve weeks, **four phases**, with the overlaps shown honestly.",
     "desc": "A gantt makes dependencies visible. Phase 3 starts before Phase 2 "
             "fully closes, on purpose: golden paths are designed while the foundation settles.",
     "units": 12,
     "bars": [("Phase 1 \u00b7 Assess", "blue", 0, 3, "Weeks 1-3"),
              ("Phase 2 \u00b7 Foundation", "green", 3, 6, "Weeks 4-9"),
              ("Phase 3 \u00b7 Golden paths", "yellow", 6, 4, "Weeks 7-10, overlaps"),
              ("Phase 4 \u00b7 Scale", "red", 9, 3, "Weeks 10-12+")],
     "src": "**Timeline note \u00b7** Weeks assume a mid-size org with an existing Azure footprint."},
    {"type": "team", "sec": "plan", "kicker": "The engagement team",
     "h": "Four roles, **clear ownership**, no ambiguity about who decides what.",
     "desc": "A small team by design. Each person owns one thing, and two of the "
             "four seats are filled by the client so the hand-over starts on day one.",
     "people": [
        ("PS", "Frontier Cockpit Team", "Engagement lead", "Software Global Black Belt. Owns the technical direction and the client relationship end to end."),
        ("AE", "Account exec", "Commercial owner", "Holds scope, timeline, and the commercial conversation. Single point for contracting."),
        ("PE", "Platform engineer", "Build lead", "Stands up the landing zone and the standard pipeline. Pairs with client engineers."),
        ("CE", "Client engineer", "Embedded", "Two client engineers work inside the engagement, so ownership transfers as the platform is built."),
     ],
     "src": "**Staffing note \u00b7** Role names are generic. A real deck names individuals and tenure."},
    {"type": "raci", "sec": "plan", "kicker": "Ownership matrix",
     "h": "Who is **responsible, accountable, consulted, informed** for each workstream.",
     "desc": "A RACI matrix removes the most common engagement failure: ambiguity "
             "about who owns what. Each cell is one letter; ownership shifts to the client.",
     "roles": ["Client lead", "MS engagement", "Platform team", "Client ops"],
     "rows": [
        ("Platform scope & design", ["A", "C", "R", "I"]),
        ("Landing zone build", ["I", "R", "A", "C"]),
        ("CI/CD pipeline setup", ["I", "R", "A", "C"]),
        ("Policy & governance rules", ["C", "C", "A", "R"]),
        ("Pilot workload migration", ["C", "A", "R", "C"]),
        ("Platform ownership, ongoing", ["A", "I", "C", "R"]),
     ],
     "src": "**RACI note \u00b7** One accountable party per row. Calibrate the grid with the client."},
    {"type": "risks_table", "sec": "plan", "kicker": "Engagement risks",
     "h": "The honest version: **what could go wrong**, and how each is handled.",
     "desc": "A proposal without a risk slide is a sales pitch. Each row pairs a "
             "real risk with a concrete mitigation already in the plan.",
     "rows": [
        ("Teams resist a shared platform", TAG_MED, TAG_HI,
         "Two pilot teams co-design the golden paths in Phase 3, so the platform reflects real workflows."),
        ("Scope expands mid-engagement", TAG_HI, TAG_MED,
         "Phase 1 ends with a signed scope document. Changes are explicit re-scopes, not silent creep."),
        ("Existing Azure footprint conflicts", TAG_MED, TAG_MED,
         "The assessment maps the current estate first. The landing zone is designed around what exists."),
        ("Hand-over leaves a knowledge gap", TAG_MED, TAG_HI,
         "Client engineers work inside Phases 2 and 3, not just at the end. Ownership transfers gradually."),
        ("Platform value is hard to prove", TAG_WATCH, TAG_MED,
         "The Phase 1 baseline is the comparison point. Later metrics read against the client's own start line."),
     ],
     "pull": ("Why this slide exists", "Naming risks early is what makes the rest "
              "of the proposal **credible**. Every mitigation here is already a line in the roadmap.",
              "Synthesis line \u00b7 reference template"),
     "src": "**Banding note \u00b7** Likelihood and impact are qualitative. Calibrate during the assessment."},

    # ===== SECTION 6 · INVESTMENT (46-48) =====
    {"type": "divider", "sec": "invest", "act_no": "VI", "kicker": "Section 6 \u00b7 Investment",
     "title": "What it takes, and what it returns",
     "desc": "The plan is set. This section is the investment shape: three "
             "engagement sizes, the specific ask, and the recommendation.",
     "questions": ["What does each engagement size include?",
                   "What is the specific first ask?"], "q_start": 16},
    {"type": "pricing", "sec": "invest", "kicker": "Investment shape",
     "h": "Three engagement sizes. **Each ends with something usable**, none locks in the next.",
     "desc": "Figures are placeholders. The point is the shape: a small committed "
             "first step, a foundation phase, and a full rollout chosen on evidence.",
     "tiers": [
        ("Tier 1 \u00b7 Assess", "3 wks", "\u00b7 fixed", "Low commitment, high clarity",
         ["Workload and blocker inventory", "Delivery and cost baseline",
          "Prioritized platform scope", "Go or no-go recommendation"],
         "Ends with **the client's own data** and a clear decision point.", False, ""),
        ("Tier 2 \u00b7 Foundation", "6 wks", "\u00b7 scoped", "The platform baseline, stood up",
         ["AKS landing zone live", "Identity and networking established",
          "Standard CI/CD path wired", "One workload running end to end"],
         "Ends with a **working platform** and one production workload on it.", True, "Most common start"),
        ("Tier 3 \u00b7 Scale", "Ongoing", "\u00b7 phased", "Rollout and hand-over",
         ["Golden-path templates published", "Remaining teams onboarded",
          "Ownership transferred to client", "Continuous improvement loop"],
         "Ends with the platform **owned and run by the client** team.", False, ""),
     ],
     "src": "**Pricing note \u00b7** Durations are illustrative. Real proposals carry costed figures."},
    {"type": "recommendation", "sec": "invest", "kicker": "Recommendation",
     "h": "Start with a **three-week assessment**. Decide the platform scope on evidence.",
     "desc": "The assessment is low-commitment and produces the client's own "
             "baseline. Everything after it is a decision the client makes with real numbers.",
     "pillars": [
        ("01", "Immediate \u00b7 the assessment", "Three weeks, fixed scope. Produces a baseline of delivery metrics and a prioritized blocker list."),
        ("02", "Near-term \u00b7 the foundation", "Stand up the landing zone and standard pipeline. First pilot team onboarded by week nine."),
        ("03", "Sustained \u00b7 the handover", "Platform ownership transfers to the client team with golden paths and an improvement loop in place."),
     ],
     "ask_label": "The ask", "ask_n": "3 wks",
     "ask_desc": "to a decision backed by **the client's own data**, not assumptions.",
     "next_label": "Next step",
     "next_text": "Confirm an assessment window and the two candidate workloads to baseline.",
     "contact": "Contact \u00b7 **frontier-cockpit@example.com**",
     "src": "**This is a reference template.** Structure, palette, and component set are the deliverable; content is illustrative."},

    # ===== BACK MATTER (49-53) =====
    {"type": "appendix_divider", "sec": "back"},
    {"type": "cover_stat", "sec": "front"},
    {"type": "cover_thesis", "sec": "front"},
    {"type": "cover_pillars", "sec": "front"},
    {"type": "contact", "sec": "back"},
]
